apiVersion: v1
kind: Service
metadata:
  name: {{ include "smpweb-nuxt.fullname" . }}
  labels:
    {{- include "smpweb-nuxt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

  selector:
    {{- include "smpweb-nuxt.selectorLabels" . | nindent 4 }}
